### ISSUE TITLE
Support for PMD 1.6X is broken

### ISSUE THREAD

**Issue by halamix2** [StuntKit/stunt_gp_blender#2]
When trying to load 1.60 CAR1.pmd:
```
try 10 36 poly 135 mesh 1 lod 0


Traceback (most recent call last):
  File "import_pmd.py", line 63, in execute
    result = self.to_blender_basic(pmd, self.filepath, name, self.scale)
  File "import_pmd.py", line 186, in to_blender_basic
    tab = [uvs[k].vertex_id for k in faces_extracted]
  File "import_pmd.py", line 186, in <listcomp>
    tab = [uvs[k].vertex_id for k in faces_extracted]
IndexError: list index out of range
Saved session recovery to '/tmp/quit.blen
```

**Comment by halamix2** [comment]
1.62 should work now
